travis:
  secure:
    BINSTAR_TOKEN: GKtE0yDZMsXferpad3lmjPPxhRQrsOlf5IMdEKLZZpPQnclrRibKp7Ikn0IOQ1Um69pOihIf8LmGdmgKvNGrWWi4/ZxbObqi9IeDx8G7mEiBcFYDiy5KSEENAYscHcB1gA4S5FNJzV8BuOkEhCRvr1/QssFyQBCisqZILaScfMGXdnJlIKSqB890anPtMQSfs4G79wGbSipcU1ej33JwQo3qsBWYOVJaEpSfFT/zSCVaobVA5pIPEozDrsHCqY5FEw23h3As4vPpV9bfAocpGTbE3mGbTC+pbhItX4+O669oq93ZXhabU0WnbvO3XzHMy89bbfPKoKKwTyD+omLBYSdf07JKKQf9/HyNJbCJ4dHuOxr9YXqjjt+nxvT7q5ntP0LOO/GCRyg3HFcFAIpDUR7Ht7V7ghpa+X+AffA4Gs3wtXFaeKsobwvmXBJpdNdbnasFOpylxETlHj7RwLh82h1ugI6kvShuCsYg43wPIivYZk8yAFhQb1o6OMxfrmFgAh0pW68G7o3KAy4r5GFRtmWFYwWsbXe30MNEJCFHxB9zLsm48KuRNCdJKjdkdJPl3WVxFKRG9qn0j31xYsYlbYrwwmofM6iaYIGv/Whfm04jr0CfTBFONrzytjLg9voNCNmeo+IjYDuxbvOSvifv6fVfYBWF9wTqqmgHujhpRQQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
